---
 - name: deploy war file
   hosts: containers
   vars:
     tomcat_folder: "//usr/local/tomcat/webapps/"
     tomcat_path: "/usr/local/tomcat/"
   tasks:  
     - name: stop tomcat
       command: sh "{{ tomcat_path }}/bin/shutdown.sh"
     - name: deploy war
       copy: 
         src: /var/lib/jenkins/workspace/BUILD1/target/*.war
         dest: "{{ tomcat_folder}}"
     - name: start tomcat
       command: sh "{{ tomcat_path }}/bin/startup.sh"
