---
 - name: deploy war file
   hosts: containers
   vars:
     tomcat_folder: "//usr/local/tomcat/webapps/"
     tomcat_path: "/usr/local/tomcat/"
     - name: deploy war
       copy: 
         src: /var/lib/jenkins/workspace/BUILD1/target/myweb-0.0.7.war
         dest: "{{ tomcat_folder}}"
         remote_src: no
     - name: start tomcat
       command: sh "{{ tomcat_path }}/bin/startup.sh"
